### ISSUE TITLE
Bug of the SSL testing

### ISSUE THREAD

**Issue by tangtaogo** [Nightmare-n/UniPAD#13]
Hello,
Thank you for your excellent work!
There is a bug in the test of UVTRSSL:
https://github.com/Nightmare-n/UniPAD/blob/2de0c0544f2951fa67bcba2e8dec9f7fc6a80a39/projects/mmdet3d_plugin/models/detectors/uvtr_ssl.py#L257
The passed parameters do not match the definition:
https://github.com/Nightmare-n/UniPAD/blob/2de0c0544f2951fa67bcba2e8dec9f7fc6a80a39/projects/mmdet3d_plugin/models/dense_heads/render_head.py#L84
It seems that the forward_test function in render_head was forgotten to be committed.
Looking forward to your response.

**Comment by tangtaogo** [comment]
Also in the test of UVTRSSL:
https://github.com/Nightmare-n/UniPAD/blob/2de0c0544f2951fa67bcba2e8dec9f7fc6a80a39/projects/mmdet3d_plugin/models/detectors/uvtr_ssl.py#L264
the vis_weights is not define

**Comment by DingYikang** [comment]
Hi, same question. Is there any update?

**Comment by Nightmare-n** [comment]
I have updated the code (not strictly tested). Please try again.

**Comment by tangtaogo** [comment]
Thanks !!!!
