### ISSUE TITLE
Question about rendering results in the paper (Figure 3)

### ISSUE THREAD

**Issue by hottruong98** [Nightmare-n/UniPAD#15]
Hi. Thank you for your great work.

May I ask you some questions regarding how you get the rendering results in Figure 3 of your published paper?

Did you use the frozen pretrained unipad-c (without masking the input images) to render both rgb and depth images? And here, the number of rays to sample is corresponding to the image resolution (like 928x1600 rays per each camera view or 928 // k x 1600 //k rays,....,?

Thank you.

**Comment by Nightmare-n** [comment]
Hi, thanks for your interest!

1. Yes. We do not mask the input image when rendering Figure 3.

2. The resolution of the rendered image is 928 // k x 1600 //k, so we sample 928 // k x 1600 //k rays during inference.

**Comment by hottruong98** [comment]
Ok. Thank you for your response.
