### ISSUE TITLE
About rendering

### ISSUE THREAD

**Issue by Doctor-James** [Nightmare-n/UniPAD#3]
Thank you for your work. I would like to ask how sampling 512 rays per image view achieves such a high rendering resolution in the final render image(figure3 in your paper). For a high-definition image of 1600 900, 512 seems like a very small number.

**Comment by Nightmare-n** [comment]
Hi, thanks for your interest! During training, we only sample 512 rays for supervision. During inference (visualization), all 1600 \* 900 rays are used to render the image.
