### ISSUE TITLE
Question about point feature

### ISSUE THREAD

**Issue by tjzhym** [Nightmare-n/UniPAD#6]
when i debug with you code, found that there is no pts_voxel_encoder, thus there is no pts_feat of the output.
I can only found you use point surpervise the sdf in "sparse_points_sdf_supervised"?

So how do you use lidar input like your paper?

**Comment by Nightmare-n** [comment]
Thanks for your interest! We currently only release the code for image modality, and the complete code (for point modality and multi-modality) will be released soon.
