### ISSUE TITLE
are there Pointcloud_Backbone? Only img_backbone?

### ISSUE THREAD

**Issue by qinghuizhao** [Nightmare-n/UniPAD#7]
are there Pointcloud_Backbone? Only img_backbone?

**Comment by qinghuizhao** [comment]
are there Pointcloud_Backbone? Only img_backbone?

**Comment by HaoyiZhu** [comment]
Hi, for point cloud backbone, you can refer to [PonderV2](https://github.com/OpenGVLab/PonderV2)
