### ISSUE TITLE
About running code

### ISSUE THREAD

**Issue by wangq0688** [Nightmare-n/UniPAD#8]
Hello, thanks for your excellent work! I have downloaded nuScenes dataset. Can you provide an explanation of running test data?

**Comment by Hongbin98** [comment]
@wangq0688  I have met the same issue. Did you solve this problem?

**Comment by Nightmare-n** [comment]
Thanks for your interest! The following command would meet your request:
```python
PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python3 -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    $(dirname "$0")/test.py $CONFIG $CHECKPOINT --launcher pytorch --eval bbox
```
